baseURL: https://www.graphlab.fr/
languageCode: fr-FR
title: GraphLab
theme: xmin

params:
  description: "Équipe de recherche"
  keywords:
    - graphe
    - document
    - donnée
    - corpus
    - visualisation
    - publication
    - web
  authors:
    - Arthur Perret

menu:
  main:
    - name: Projets
      url: "projets/"
      weight: 1
